# Generated by Django 5.2.7 on 2025-10-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticador', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rights',
            field=models.BooleanField(default=False),
        ),
    ]
