# Generated by Django 5.2.7 on 2025-10-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticador', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
