# Generated by Django 5.2.7 on 2025-10-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticador', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rights',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
